### ISSUE TITLE
Typography 적용한 css 믹스인 작성

### ISSUE THREAD

**Issue by bok000111** [42Where/where42_front_v2#15]
피그마 Typography 기반으로 공통적으로 사용할 수 있는 기본 text 구현

atom level component 로 구현하면 될 것 같습니다.

추후에 bold, title같은 바리에이션도 구현 필요할것같습니다

**Comment by mg5566** [comment]
mixin 기능 사용을 위해서 sass 를 사용합니다.
https://sass-lang.com/

next js 에 sass 적용하기
https://nextjs.org/docs/app/building-your-application/styling/sass
storybook 에 sass 적용하기
https://storybook.js.org/recipes/sass#recipe-section
